version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: splititright_server_prod
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=4000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: splititright_db_prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - splititright_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  splititright_db_data:
